# Generated by Django 4.2.4 on 2023-09-07 12:07

from django.db import migrations
import users.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.manager.CustomUserManager()),
            ],
        ),
    ]
