# Generated by Django 4.2.4 on 2023-08-21 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование курса')),
                ('course_preview', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('course_comment', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование урока')),
                ('lesson_preview', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('lesson_comment', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('lesson_url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('course_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.course')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
