# Generated by Django 4.2.4 on 2023-09-29 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_alter_payments_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.course', verbose_name='Сумма оплаты'),
        ),
    ]
