# Generated by Django 4.2.4 on 2023-09-05 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learn', '0004_alter_payments_paid_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment',
            field=models.IntegerField(verbose_name='Сумма оплаты'),
        ),
    ]
