# Generated by Django 4.2.4 on 2023-10-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_alter_payments_payment_alter_payments_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ID оплаты'),
        ),
    ]
